### PR TITLE
Upgrade project to latest SDK

### PR DESCRIPTION
**Pull request by refapp-machine-da**

### CODE REVIEW

**Comment by sullivan-da** [comment]
This looks fine to me, all checks pass.

**Comment by sullivan-da** [comment]
I don't see any references to `javaapi.data.Record` in this project

**Review by sullivan-da — APPROVED** [review]

**Comment by tamaskalcza-da** [comment]
> I don't see any references to `javaapi.data.Record` in this project

There is no Java any more besides an integration test.

**Comment by sullivan-da** [comment]
@tamaskalcza-da do you want to merge? i am not authorized to do so

**Review by tamaskalcza-da — APPROVED** [review]

**Comment by tamaskalcza-da** [comment]
@sullivan-da Apparently me neither.

**Comment by sullivan-da** [comment]
@tamaskalcza-da i just gave you and me admin access on this repo and will merge now 🙂

**Pull request merged**
